Various fixes
- ipmi config for supermicro nodes
- secured domain config
- included node name in specific pxe boot menus
- fixed root password loading
- synology workaround for sftp

diff --git a/bin/power b/bin/power
--- a/bin/power
+++ b/bin/power
@@ -9,6 +9,10 @@ while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symli
 done
 DIR="$( cd -P "$( dirname "$SOURCE" )" >/dev/null && pwd )"
 
+if [ "$#" -lt 1 ]; then
+    >&2 echo "ERROR: Illegal number of parameters: $0 <hostname>"
+    exit
+fi
 (
     cd $DIR/..
     ansible-playbook -l $1 playbooks/power.yml -e state=${2:-on}
